### PR TITLE
Make `List.repeatWith` and `List.range` generic

### PR DESCRIPTION
**Pull request by brekk**

### CODE REVIEW

**Comment by brekk** [comment]
This issue is linked as the new tests aren't format-able: https://github.com/madlib-lang/madlib/issues/146

**Review by aboeglin — COMMENTED** [review]
I’m confused, why not just make List.range generic?

**Comment by brekk** [comment]
> I’m confused, why not just make List.range generic?

Ah, I'm open to that, but my original thinking was that `range` seems like it ought to be not part of List at all. `Short.range` / `Integer.range` makes intuitive sense to me, but `List.range` feels like it's only associated with lists by happenstance.

**Comment by aboeglin** [comment]
Well, in a way it’s a List constructor after all.

**Review by aboeglin — APPROVED** [review]
Forgot about that one, it can go as well!

**Pull request merged**
